<?php

con=mysql_connect(localhost,root,);
mysql_select_db(resume);

?>
<?php

$detail=array(  
  `username` ,
    `name` ,
  `password`  ,
  `profession` ,
  `dob`,
  `birth_city`  ,
  `birth_country`  ,
  `profile_link`  ,
  `work_duration1` ,
  `organisation1`  ,
  `job_place1`  ,
  `job_description1`,
  `work_duration2`  ,
  `organization2`  ,
  `job_place2`  ,
  `job_description2`  ,
  `your_post2`  ,
  `edu_duration1`  ,
  `institute1`  ,
  `degree1`  ,
  `edu_place1`  ,
  `edu_description1`  ,
  `institute2`  ,
  `degree2`  ,
  `edu_description2`  ,
  `edu_place2`  ,
  `proskill1`  ,
  `psv1`  ,
  `proskill2`  ,
  `psv2` ,
  `proskill3`  ,
  `psv3`  ,
  `pskill1`  ,
  `persv1`  ,
  `pskill2`  ,
  `persv2` ,
  `pskill3`  ,
  `persv3`  ,
  `int_name1` ,
  `int_description1` ,
  `int_name2` ,
  `int_description2` ,
  `int_name3` ,
  `int_description3` ,
  `address1`  ,
  `address2`  ,
  `mobile_no`  ,
  `phone_no` ,
  `email_id`  ,);
  ?>



