<html>
<head>

<link rel="stylesheet" type="text/css" href="resumehome2.css"/>


<style>
body{background-color: #cfcdcd}
img{
		
		border-radius:70%;
		
       
	}
	#table1{
		margin-left: 37%;
		margin-top: 2%;
		margin-right: 40%;
		border-spacing: 4px;
	}
	



img{
	background-color: rgba(248, 247, 216, 0.7);
}
#tab1{
	position: absolute;
	top:420;
	margin-right: 18%;
}
#tab3{
	position: absolute;
	top:200;
	margin-right: 18%;
}
#tab2{
	position: absolute;
	top:310;
 margin-right: 18%;
}
#sirlayer{
	width:100% ;
	height:133;
	background-color: black;
opacity: 0.3;
    filter: alpha(opacity=60);
    border-radius: 70%;
   margin-top: -133px; 
}
#layer{
	width:90% ;
	height:90;
	background-color: black;
opacity: 0.3;
    filter: alpha(opacity=60);
    border-radius: 70%;
	
margin-top: -90px;
}
#tab1{

}
#table4{


	margin-left: 14%;
	margin-right: 18%;
    
		margin-top:2%;
}
#imageedit{
	width:5%;
	height:5%;


}
/*#table_left2{
    padding-left: 2px;
	/*border-right:8px ridge #535151;*/
}

#table_left1{
    padding-right: 7px;
	/*border-right:8px ridge #535151;*/
}
</style>


</head>
<title></title>
<body>

<div id="signup">
           <div id="clubtecho">CLUB TECHNOCRATS</div>

         <div id="resume">RESUME BUILDER</div>
         
    <form class="submit" action="fet.php">
           <div id="enteryourname"> <input type="text" id="nameinput" placeholder="Name"></div>
           <div id="mobileno"><input type="text" id="mobileinput" placeholder="Mobile no"><input id="submit" type="submit" value="icon"></div>
  

     </form>
</div>
<div id="BelowSignUp" >
      <div id="table1">
         <table width="100%">
         <tr>
         <td id="table_left1" width="50%" ><div id="image1" ><img src="1.jpg" width="100%" height="133px"></div><div id="sirlayer"></div></td>
         <td id="table_left2"  width="50%" style="padding:3px"><img src="1.jpg" width="100%" height="133px"><div id="sirlayer"></div></td>
        </tr>
        </table>
       </div>

   <div id="table4" > 
    <table>
      <tr id="tab1">
         
         <td id="table_left"  width="10.1%"><img src="1.jpg" width="90%" height="90"><div id="layer"></div></td>
         <td id="table_left"  width="10.1%"><img src="1.jpg" width="90%" height="90"><div id="layer"></div></td>
         <td id="table_left"  width="10.1%"><img src="1.jpg" width="90%" height="90"><div id="layer"></div></td>
         <td id="table_left"  width="10.1%" ><img src="1.jpg" width="90%" height="90"><div id="layer"></div></td>
         <td id="table_left"  width="10.1%" ><img src="1.jpg" width="90%" height="90"><div id="layer"></div></td>
         <td id="table_left"  width="10.1%" ><img src="1.jpg" width="90%" height="90"><div id="layer"></div></td>
         <td id="table_left"  width="10.1%" ><img src="1.jpg" width="90%" height="90"><div id="layer"></div></td>
         <td id="table_left" width="10.1%" ><img src="1.jpg" width="90%" height="90"><div id="layer"></div></td>
        
      </tr>
      <tr id="tab2">
         
         <td id="table_left"  width="10.1%" ><img src="1.jpg" width="90%" height="90"><div id="layer"></div></td>
         <td id="table_left"  width="10.1%" ><img src="1.jpg" width="90%" height="90"><div id="layer"></div></td>
         <td id="table_left"  width="10.1%" ><img src="1.jpg" width="90%" height="90"><div id="layer"></div></td>
         <td id="table_left"  width="10.1%" ><img src="1.jpg" width="90%" height="90"><div id="layer"></div></td>
         <td id="table_left"  width="10.1%" ><img src="1.jpg" width="90%" height="90"><div id="layer"></div></td>
         <td id="table_left" width="10.1%" ><img src="1.jpg" width="90%" height="90"><div id="layer"></div></td>
         <td id="table_left"  width="10.1%" ><img src="1.jpg" width="90%" height="90"><div id="layer"></div></td>
         <td width="10.1%" ><img src="1.jpg" width="90%" height="90"><div id="layer"></div><div id="layer"></div></td>
         </tr>
  
      <tr id="tab3" >
         
         <td id="table_left"  width="10.1%"><img src="1.jpg" width="90%" height="90"><div id="layer"></div></td>
         <td id="table_left"  width="10.1%" ><img src="1.jpg" width="90%" height="90"><div id="layer"></div></td>
         <td id="table_left"  width="10.1%" ><img src="1.jpg" width="90%" height="90"><div id="layer"></div></td>
         <td id="table_left"  width="10.1%" ><img src="1.jpg" width="90%" height="90"><div id="layer"></div></td>
         <td id="table_left"  width="10.1%" ><img src="1.jpg" width="90%" height="90"><div id="layer"></div></td>
         <td id="table_left" width="10.1%" ><img src="1.jpg" width="90%" height="90"><div id="layer"></div></td>
         <td id="table_left"  width="10.1%" ><img src="1.jpg" width="90%" height="90"><div id="layer"></div></td>
         <td width="10.1%" ><img src="1.jpg" width="90%" height="90"><div id="layer"></div></td>
         </tr>
         </table>
    </div>
</div>
</body>
</html>